plugins {
    id 'fabric-loom' version '1.11.8'
    id 'maven-publish'
}

apply from: rootProject.file('gradle/charmony-common.gradle')

def bundledProjects = [
    ':charmony-api',
    ':charmony',
    ':charmony-azalea-wood',
    ':charmony-brew-and-stew',
    ':charmony-collection',
    ':charmony-decor',
    ':charmony-ebony-wood',
    ':charmony-glint-colors',
    ':charmony-mooblooms',
    ':charmony-totem-of-preserving',
    ':charmony-tweaks'
]

dependencies {
    bundledProjects.each { path ->
        implementation project(path: path, configuration: 'namedElements')
        include project(path)
    }

    include implementation("com.electronwill.night-config:core:${night_config_version}")
    include implementation("com.electronwill.night-config:toml:${night_config_version}")
    include implementation("com.moandjiezana.toml:toml4j:${toml4j_version}")
    include implementation("org.apache.commons:commons-lang3:${commons_lang_version}")
    include modImplementation("io.github.llamalad7:mixinextras-fabric:${mixinextras_version}")
}
