pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'charm'

def modules = [
    'charmony-api',
    'charmony',
    'charmony-azalea-wood',
    'charmony-brew-and-stew',
    'charmony-collection',
    'charmony-decor',
    'charmony-ebony-wood',
    'charmony-glint-colors',
    'charmony-mooblooms',
    'charmony-totem-of-preserving',
    'charmony-tweaks'
]

modules.each { moduleName ->
    include(":${moduleName}")
    def descriptor = project(":${moduleName}")
    descriptor.projectDir = file("modules/${moduleName}")
    descriptor.buildFileName = '../../gradle/charmony-module.gradle'
}
